import { useEffect, useRef, useState } from 'react';
import { Check, CircleHelp, Download, Sparkles, Trash2, Upload, Zap } from 'lucide-react';
import { createBackup, parseBackupPayload, DEFAULT_PROFILE, FOCUS_SOUNDSCAPES, FOCUS_SOUNDSCAPE_LABELS, PROFILE_ROLE_LABELS, PROFILE_ROLES } from '../lib/storage.js';
import { makeCourse, validateProfileInput, validateSemesterInput } from '../lib/domain.js';
import { requestNotifyPermission } from '../lib/reminders.js';
import { ConfirmDialog } from '../components/ui.jsx';
import { CourseManager } from '../components/CourseForm.jsx';

export function SettingsPage({ data, commit, updatePreferences, onStartTutorial, onResetWorkspace }) {
  const [profile, setProfile] = useState(data.profile);
  const [semester, setSemester] = useState(data.semester || { name: '', startDate: '', endDate: '' });
  const [status, setStatus] = useState({ text: '', error: false });
  const [confirm, setConfirm] = useState(null);
  const fileRef = useRef(null);
  useEffect(() => setProfile(data.profile), [data.profile]);
  useEffect(() => setSemester(data.semester || { name: '', startDate: '', endDate: '' }), [data.semester]);
  const saveProfile = (event) => { event.preventDefault(); const validation = validateProfileInput(profile); if (validation) { setStatus({ text: validation.message, error: true }); return; } commit((current) => ({ ...current, profile: { ...current.profile, name: profile.name.trim(), role: profile.role, goal: profile.goal.trim(), tagline: profile.tagline.trim() || DEFAULT_PROFILE.tagline }, onboarding: { ...current.onboarding, profileCompleted: true } })); setStatus({ text: 'Profil tersimpan.', error: false }); };
  const saveSemester = (event) => {
    event.preventDefault();
    const validation = validateSemesterInput(semester);
    if (validation) { setStatus({ text: validation.message, error: true }); return; }
    commit((current) => ({ ...current, semester: semester.name.trim() || semester.startDate || semester.endDate ? { name: semester.name.trim() || 'Semester berjalan', startDate: semester.startDate || null, endDate: semester.endDate || null } : null }));
    setStatus({ text: 'Semester disimpan.', error: false });
  };
  const exportData = () => { const blob = new Blob([JSON.stringify(createBackup(data), null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'taskflow-backup.json'; anchor.click(); URL.revokeObjectURL(url); setStatus({ text: 'Backup berhasil dibuat.', error: false }); };
  const importData = async (event) => { const file = event.target.files?.[0]; if (!file) return; try { const parsed = parseBackupPayload(JSON.parse(await file.text())); setConfirm({ type: 'import', data: parsed, title: 'Pulihkan backup ini?', message: `Backup berisi ${parsed.tasks.length} tugas dan ${parsed.courses.length} mata kuliah, dan akan menggantikan data lokal saat ini.` }); } catch (error) { setStatus({ text: error.message || 'File JSON tidak bisa dibaca.', error: true }); } event.target.value = ''; };
  const resetAll = () => setConfirm({ type: 'reset', title: 'Mulai workspace baru?', message: 'Tugas, mata kuliah, profil, sesi fokus, XP, preferensi, dan status tutorial di perangkat ini akan dihapus. Kamu akan kembali ke pengisian profil.' });
  const confirmAction = async () => { if (confirm?.type === 'import') { commit(() => confirm.data); setStatus({ text: 'Data berhasil dipulihkan.', error: false }); } if (confirm?.type === 'reset') { try { await onResetWorkspace(); } catch { setStatus({ text: 'Workspace belum dapat direset.', error: true }); } } setConfirm(null); };
  const saveCourse = (input, id) => commit((current) => {
    const course = makeCourse(input, id || Date.now());
    const courses = id ? current.courses.map((item) => item.id === id ? { ...item, ...course, id } : item) : [...current.courses, course];
    return { ...current, courses, onboarding: { ...current.onboarding, coursesIntroDismissed: true } };
  }, id ? 'Mata kuliah diperbarui.' : 'Mata kuliah ditambahkan.');
  const deleteCourse = (course) => commit((current) => ({
    ...current,
    courses: current.courses.filter((item) => item.id !== course.id),
    tasks: current.tasks.map((task) => task.courseId === course.id ? { ...task, courseId: null } : task)
  }), 'Mata kuliah dihapus. Tugas terkait tetap ada.');
  const enableNotify = async () => {
    const permission = await requestNotifyPermission();
    if (permission === 'granted') { updatePreferences({ notify: true }); setStatus({ text: 'Pengingat browser diizinkan. Berjalan saat TaskFlow terbuka.', error: false }); }
    else setStatus({ text: 'Izin notifikasi belum diberikan.', error: true });
  };
  return <section className="settings-layout"><div className="settings-main">
    <article className="card settings-card" id="courses"><div className="card-header"><div><p className="section-kicker">Mata kuliah</p><h2>Daftar yang sedang kamu jalani</h2></div><span className="card-icon"><Sparkles size={18} /></span></div><CourseManager courses={data.courses} onSave={saveCourse} onDelete={deleteCourse} /></article>
    <article className="card settings-card"><div className="card-header"><div><p className="section-kicker">Semester</p><h2>Bingkai waktu opsional</h2></div></div><form className="form-stack" onSubmit={saveSemester}><div className="field-group"><label htmlFor="semester-name">Nama semester</label><input id="semester-name" className="input" value={semester.name || ''} onChange={(event) => setSemester((current) => ({ ...current, name: event.target.value }))} placeholder="Ganjil 2026" /></div><div className="form-grid-two"><div className="field-group"><label htmlFor="semester-start">Mulai</label><input id="semester-start" className="input" type="date" value={semester.startDate || ''} onChange={(event) => setSemester((current) => ({ ...current, startDate: event.target.value }))} /></div><div className="field-group"><label htmlFor="semester-end">Selesai</label><input id="semester-end" className="input" type="date" value={semester.endDate || ''} onChange={(event) => setSemester((current) => ({ ...current, endDate: event.target.value }))} /></div></div><p className="muted">Tanggal ini dipakai Analitik untuk memfilter tugas dan sesi fokus semester berjalan.</p><button className="btn btn-secondary" type="submit">Simpan semester</button></form></article>
    <article className="card settings-card"><div className="card-header"><div><p className="section-kicker">Profil</p><h2>Ruang kerja yang terasa milikmu</h2></div><span className="card-icon"><Sparkles size={18} /></span></div><form className="form-stack" onSubmit={saveProfile}><div className="field-group"><label htmlFor="profile-name">Nama panggilan</label><input id="profile-name" className="input" maxLength={40} value={profile.name} onChange={(event) => setProfile((current) => ({ ...current, name: event.target.value }))} /></div><div className="field-group"><label htmlFor="profile-role">Peran</label><select id="profile-role" className="input" value={profile.role} onChange={(event) => setProfile((current) => ({ ...current, role: event.target.value }))}><option value="">Pilih peran</option>{PROFILE_ROLES.map((role) => <option key={role} value={role}>{PROFILE_ROLE_LABELS[role]}</option>)}</select></div><div className="field-group"><label htmlFor="profile-goal">Tujuan utama</label><textarea id="profile-goal" className="input" maxLength={120} value={profile.goal} onChange={(event) => setProfile((current) => ({ ...current, goal: event.target.value }))} placeholder="Contoh: Menyelesaikan proyek akhir dengan lebih teratur" /></div><div className="field-group"><label htmlFor="profile-tagline">Tagline <span className="label-hint">opsional</span></label><input id="profile-tagline" className="input" maxLength={80} value={profile.tagline} onChange={(event) => setProfile((current) => ({ ...current, tagline: event.target.value }))} placeholder="Pelan-pelan tapi selesai" /></div><div className="action-row"><button className="btn btn-primary" type="submit"><Check size={16} />Simpan profil</button>{status.text && <span className={status.error ? 'form-status form-status-error' : 'form-status'} role="status">{status.text}</span>}</div></form></article>
    <article className="card settings-card"><div className="card-header"><div><p className="section-kicker">Tampilan dan fokus</p><h2>Atur rasa interaksinya</h2></div><span className="card-icon"><Zap size={18} /></span></div><div className="settings-options">
      <label className="setting-row"><span><strong>Tema</strong><small>Gelap, terang, atau mengikuti perangkat.</small></span><select className="input setting-select" value={data.preferences.theme} onChange={(event) => updatePreferences({ theme: event.target.value })}><option value="system">Ikuti perangkat</option><option value="light">Terang</option><option value="dark">Gelap</option></select></label>
      <label className="setting-row"><span><strong>Motion</strong><small>Kurangi gerak jika kamu ingin layar lebih tenang.</small></span><select className="input setting-select" value={data.preferences.motion} onChange={(event) => updatePreferences({ motion: event.target.value })}><option value="full">Penuh</option><option value="compact">Ringkas</option><option value="system">Ikuti perangkat</option></select></label>
      <label className="setting-row"><span><strong>Preset Focus Run</strong><small>Durasi awal untuk tombol mulai di Beranda.</small></span><select className="input setting-select" value={data.preferences.focusPreset} onChange={(event) => updatePreferences({ focusPreset: Number(event.target.value) })}><option value="25">25 menit</option><option value="50">50 menit</option></select></label>
      <label className="setting-row"><span><strong>Bunyi selesai sesi</strong><small>Chime singkat saat Focus Run berakhir.</small></span><input type="checkbox" checked={data.preferences.sound} onChange={(event) => updatePreferences({ sound: event.target.checked })} /></label>
      <label className="setting-row"><span><strong>Soundscape Focus Run</strong><small>Musik lokal dari aset aplikasi, tanpa streaming.</small></span><select className="input setting-select" value={data.preferences.focusSoundscape} onChange={(event) => updatePreferences({ focusSoundscape: event.target.value })}>{FOCUS_SOUNDSCAPES.map((soundscape) => <option key={soundscape} value={soundscape}>{FOCUS_SOUNDSCAPE_LABELS[soundscape]}</option>)}</select></label>
      <label className="setting-row"><span><strong>Volume soundscape</strong><small>{data.preferences.focusSoundVolume}% saat sesi fokus berjalan.</small></span><input className="range-input" type="range" min="0" max="100" value={data.preferences.focusSoundVolume} onChange={(event) => updatePreferences({ focusSoundVolume: Number(event.target.value) })} aria-label="Volume soundscape" /></label>
      <label className="setting-row"><span><strong>Pengingat browser</strong><small>Hanya berjalan saat TaskFlow terbuka atau terpasang sebagai aplikasi.</small></span><button className="btn btn-secondary" type="button" onClick={enableNotify}>{data.preferences.notify ? 'Izin sudah aktif' : 'Izinkan pengingat'}</button></label>
    </div></article>
    <article className="card settings-card"><div className="card-header"><div><p className="section-kicker">Bantuan</p><h2>Kenali TaskFlow lagi</h2></div><span className="card-icon"><CircleHelp size={18} /></span></div><p className="muted">Jalankan kembali tutorial visual tanpa mengubah data tugasmu.</p><button className="btn btn-secondary" type="button" onClick={onStartTutorial}><CircleHelp size={16} />Mulai tutorial lagi</button></article>
    <article className="card settings-card"><div className="card-header"><div><p className="section-kicker">Backup dan pemulihan</p><h2>Data tetap di perangkat ini</h2></div><span className="card-icon"><Download size={18} /></span></div><p className="muted">Backup menyimpan tugas, mata kuliah, profil, XP, sesi fokus, dan preferensi dalam satu file JSON.</p><div className="action-row"><button className="btn btn-secondary" type="button" onClick={exportData}><Download size={16} />Export JSON</button><button className="btn btn-secondary" type="button" onClick={() => fileRef.current?.click()}><Upload size={16} />Import JSON</button><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={importData} /></div></article>
    <article className="card danger-card"><div className="card-header"><div><p className="section-kicker danger-text">Perangkat bersama</p><h2>Mulai workspace baru</h2></div><span className="card-icon card-icon-danger"><Trash2 size={18} /></span></div><p className="muted">Hapus semua data lokal perangkat ini agar pengguna berikutnya dapat mengisi profil dan mengikuti tutorial dari awal.</p><button className="btn btn-danger" type="button" onClick={resetAll}><Trash2 size={16} />Mulai workspace baru</button></article>
  </div><aside className="settings-aside"><div className="settings-profile"><span className="profile-orbit"><span>{(data.profile.name || 'V').slice(0, 1).toUpperCase()}</span></span><p className="eyebrow">Level {data.progress.level}</p><h2>{data.profile.name || 'Pengguna baru'}</h2><p>{data.profile.goal || data.profile.tagline}</p><div className="aside-stats"><span><strong>{data.progress.totalXp}</strong> XP</span><span><strong>{data.progress.currentStreak}</strong> hari streak</span></div></div><div className="help-note"><CircleHelp size={18} /><div><strong>Ruang yang tenang</strong><p>TaskFlow menyimpan data di browser perangkat ini dan tidak membutuhkan akun.</p></div></div></aside><ConfirmDialog open={Boolean(confirm)} title={confirm?.title} message={confirm?.message} confirmLabel={confirm?.type === 'import' ? 'Pulihkan data' : 'Mulai baru'} danger={confirm?.type === 'reset'} onClose={() => setConfirm(null)} onConfirm={confirmAction} /></section>;
}
